### ISSUE TITLE
Undeclared dependency Path::Tiny

### ISSUE THREAD

**Issue by eserte** [team-at-cpan/Database-Async#2]
The test suite fails if Path::Tiny is not installed. Sample fail report at CPAN Testers:
http://www.cpantesters.org/cpan/report/ca961ea8-6415-11e9-8bc9-bfd6c889963f

**Comment by tm604** [comment]
Cleaning up old issues - this should be fixed in f5f0179fc7d59d88856615e514bfe346876b0bd8, thanks for reporting!
